name: Igor Vasilenko
description: iOS developer @YOTA

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'igorvasilenko.me'
gems: [jekyll-paginate]
permalink: /:title

# Details for the RSS feed generator
url:            'http://igorvasilenko.me/'
author:         'Igor Vasilenko'
