name: Igor Vasilenko
description: iOS Developer @CleverPumpkin

markdown: kramdown
highlighter: pygments
logo: true
paginate: 15
url: "https://vasilenko.tech"
baseurl:
domain_name: 'igorvasilenko.me'
gems: [jekyll-paginate]
permalink: /:title

# Details for the RSS feed generator
url:            'http://igorvasilenko.me/'
author:         'Igor Vasilenko'
