name: Igor Vasilenko
description: iOS developer @YOTA
meta_description: "Igor Vasilenko. iOS developer @YOTA"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'ivasilenko.github.io'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'ivasilenko.github.io'
author:         'Igor Vasilenko'
